# example config file: Ex0.conf
[RunControl]
# from the base RunControl.cc
EUDAQ_CTRL_PRODUCER_LAST_START = my_pd0
EUDAQ_CTRL_PRODUCER_FIRST_STOP = my_pd0
# Steer which values to display in the GUI: producerName and displayed value are seperated by a ",". 
#ADDITIONAL_DISPLAY_NUMBERS = "log,_SERVER"

[Producer.my_pd0]
# connection to the data collector
EUDAQ_DC = my_dc
# config-parameters of the example producer
EX0_PLANE_ID = 0
EX0_DURATION_BUSY_MS = 10
# EX0_ENABLE_TIMESTAMP = 0 
EX0_ENABLE_TRIGERNUMBER = 1
EX0_DEV_LOCK_PATH = mylock0

Iped = 100

Board0.Enable = 1
Board0.BaseAddress = 0x06000000
Board0.GeoAddress = 1
Board0.CrateNumber = 6

Board1.Enable = 1
Board1.BaseAddress = 0x05000000
Board1.GeoAddress = 2
Board1.CrateNumber = 5

Board2.Enable = 1
Board2.BaseAddress = 0x09000000
Board2.GeoAddress = 8
Board2.CrateNumber = 9

Board3.Enable = 1
Board3.BaseAddress = 0x88880000
Board3.GeoAddress = 9
Board3.CrateNumber = 8


[DataCollector.my_dc]
# connection to the monitor
EX0_MAX_EVENTS = 1000
EUDAQ_MN = my_mon
EUDAQ_FW = native
EUDAQ_FW_PATTERN = run$3R_$12D$X
EUDAQ_DATACOL_SEND_MONITOR_FRACTION = 10
# config-parameters of the example data collector
EX0_DISABLE_PRINT = 1


