#!/bin/bash
# cleanup of DAQ
#EUDRBIP=eudetvme001.cern.ch
EUDRBIP=mvme6100
#TLUIP=eudetpc001.cern.ch
#TLUIP=tlupc
TLUIP=zenpixell3
printf 'Killing DAQ\n'
printf '\t Cleaning up...\n'
killall RootMonitor.exe
killall TestDataCollector.exe
killall DEPFETProducerTCP.exe
ssh -Y $EUDRBIP "killall EUDRBProducer.exe" &
ssh -Y root@$TLUIP "killall TLUProducer.exe" &
killall euLog
sleep 1
killall euRun
printf '\033[1;32;48mKILLING DAQ COMPLETE, type STARTRUN to relaunch\033[0m \n'

