#!/bin/bash
# cleanup of DAQ
EUDRBIP=eudetvme001.cern.ch
TLUIP=eudetpc001.cern.ch
printf 'Killing DAQ\n'
printf '\t Cleaning up...\n'
killall RootMonitor.exe
killall TestDataCollector.exe
ssh -X -Y root@$EUDRBIP "killall EUDRBProducer.exe" &
ssh -X -Y root@$TLUIP "killall TLUProducer.exe" &
killall euLog
sleep 1
killall euRun
printf '\033[1;32;48mKILLING DAQ COMPLETE, type STARTRUN to relaunch\033[0m \n'

