#!/bin/bash
# cleanup of DAQ
PROCESSES="TestDataCollector.exe TLUProducer.exe TLUControl.exe NiProducer.exe OnlineMon.exe euLog.exe euRun.exe xterm"
for thisprocess in $PROCESSES
do
    #echo "Checking if $thisprocess is running... "
    if [ -n "`pgrep $thisprocess`" ]
    then
	echo "Killing $thisprocess"
	killall $thisprocess
    fi
done
# exit with status message if any process has been killed
printf '\033[1;32;48mKILLING DAQ COMPLETE, type STARTRUN to relaunch\033[0m \n'
