#!/bin/sh
# EUDRBIP=eudetvme001.cern.ch
# TLUIP=eudetpc001.cern.ch
EUDRBIP=mvme6100
TLUIP=tlupc

export ROOTSYS=/usr/share/root/

export HOSTNAME=eudet

cd `dirname $0`

printf 'STARTING DAQ\n'
printf '\t Cleaning up first...\n'
killall RootMonitor.exe
killall TestDataCollector.exe
ssh -X -Y eudet@$EUDRBIP "killall EUDRBProducer.exe" &
sleep 3
killall TLUProducer.exe
ssh -X -Y eudet@$TLUIP "killall TLUProducer.exe" &
#ssh -X -Y eudet@$EUDRBIP "cd /home/eudet/eudrb/Lorenzo; ./JTAGDownload_18.sh" &
sleep 12
killall euLog
sleep 1
killall euRun
printf '\033[1;32;48m\t ...Done!\033[0m \n'
sleep 1
printf '\t Starting Subprocesses\n'
printf '\t\t  RunControl\n'
cd bin
#cd gui
./euRun.app/Contents/MacOS/euRun -x 0 -y 0 -w 350 -g 450 &
sleep 1
printf '\t\t  Logger\n'
./euLog.app/Contents/MacOS/euLog -x 0 -y 450 -w 350 -g 550 &
#cd -
sleep 1
printf '\t\t  DataCollector\n'
#cd main
./TestDataCollector.exe &
#cd -
sleep 1
printf '\t\t  RootMonitor\n'
#cd root
# ./RootMonitor.exe -x 350 -y 0 -w 1330 -g 900 &
cd -
#printf '\t\t  ...Resetting EUDRBs\n'
#ssh -X -Y eudet$EUDRBIP "cd /home/eudet/eudrb/lorenzo/; ./reset > /dev/null" &
sleep 1
printf '\t\t  EUDRB\n'
ssh -X -Y eudet@$EUDRBIP "(/usr/X11R6/bin/xterm -sb -sl 1000 -geom 80x10-500-30 -fn fixed -e 'cd /home/eudet/eudaq/bin/; ./EUDRBProducer.exe -r EUDET.local')" &
sleep 2
printf '\t\t  TLU\n'
#/usr/X11/bin/xterm -sb -sl 1000 -geom 80x10-500-160 -e 'cd bin; ./TLUProducer.exe' &
ssh -X -Y eudet@$TLUIP "(xterm -sb -sl 1000 -geom 80x10-500-160 -e 'cd /home/eudet/eudaq/bin/; ./TLUProducer.exe -r EUDET.local')" &
printf '\033[1;32;48m\t ...Done!\033[0m \n'
printf '\033[1;32;48mSTART OF DAQ COMPLETE\033[0m \n'

