IF (SETUPPATH AND TESTSCRIPTPATH)
   MESSAGE(STATUS "creating directory ${SETUPPATH}")
   FILE(REMOVE_RECURSE "${SETUPPATH}/data")
   FILE(MAKE_DIRECTORY "${SETUPPATH}/data")
   FILE(MAKE_DIRECTORY "${SETUPPATH}/conf")
   configure_file(${TESTSCRIPTPATH}/test.conf "${SETUPPATH}/conf/test.conf")
ELSE (SETUPPATH AND TESTSCRIPTPATH)
   MESSAGE(FATAL_ERROR "This script requires the variables 'SETUPPATH' and 'TESTSCRIPTPATH' to be defined to create the needed directory structure for tests!")
ENDIF (SETUPPATH AND TESTSCRIPTPATH)
