/********************************************************************
* SCTDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SCTDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevSCTDict();
extern G__DLLEXPORT void G__set_cpp_environmentSCTDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableSCTDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceSCTDict();
extern G__DLLEXPORT void G__cpp_setup_typetableSCTDict();
extern G__DLLEXPORT void G__cpp_setup_memvarSCTDict();
extern G__DLLEXPORT void G__cpp_setup_globalSCTDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncSCTDict();
extern G__DLLEXPORT void G__cpp_setup_funcSCTDict();
extern G__DLLEXPORT void G__cpp_setupSCTDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "..\inc\SCTProducer.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SCTDictLN_TClass;
extern G__linked_taginfo G__SCTDictLN_TBuffer;
extern G__linked_taginfo G__SCTDictLN_TMemberInspector;
extern G__linked_taginfo G__SCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__SCTDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR;
extern G__linked_taginfo G__SCTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__SCTDictLN_TList;
extern G__linked_taginfo G__SCTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__SCTDictLN_TQObjSender;
extern G__linked_taginfo G__SCTDictLN_SCTProducer;
extern G__linked_taginfo G__SCTDictLN_SCTProducercLcLProducer_PImpl;

/* STUB derived class for protected member access */
