//
// File generated by C:\ROOT-5.34\\bin\rootcint.exe at Wed Jan 15 19:14:45 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SCTDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SCTDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void SCTProducer_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_SCTProducer(void *p = 0);
   static void *newArray_SCTProducer(Long_t size, void *p);
   static void delete_SCTProducer(void *p);
   static void deleteArray_SCTProducer(void *p);
   static void destruct_SCTProducer(void *p);
   static void streamer_SCTProducer(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::SCTProducer*)
   {
      ::SCTProducer *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SCTProducer >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SCTProducer", ::SCTProducer::Class_Version(), "./../inc/SCTProducer.h", 23,
                  typeid(::SCTProducer), DefineBehavior(ptr, ptr),
                  &::SCTProducer::Dictionary, isa_proxy, 0,
                  sizeof(::SCTProducer) );
      instance.SetNew(&new_SCTProducer);
      instance.SetNewArray(&newArray_SCTProducer);
      instance.SetDelete(&delete_SCTProducer);
      instance.SetDeleteArray(&deleteArray_SCTProducer);
      instance.SetDestructor(&destruct_SCTProducer);
      instance.SetStreamerFunc(&streamer_SCTProducer);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::SCTProducer*)
   {
      return GenerateInitInstanceLocal((::SCTProducer*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SCTProducer*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *SCTProducer::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *SCTProducer::Class_Name()
{
   return "SCTProducer";
}

//______________________________________________________________________________
const char *SCTProducer::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::SCTProducer*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SCTProducer::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::SCTProducer*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SCTProducer::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::SCTProducer*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SCTProducer::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::SCTProducer*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void SCTProducer::Streamer(TBuffer &R__b)
{
   // Stream an object of class SCTProducer.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      fQObject.Streamer(R__b);
      R__b >> m_prod;
      R__b.CheckByteCount(R__s, R__c, SCTProducer::IsA());
   } else {
      R__c = R__b.WriteVersion(SCTProducer::IsA(), kTRUE);
      fQObject.Streamer(R__b);
      R__b << m_prod;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void SCTProducer::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SCTProducer.
      typedef ::SCTProducer msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQObject", &fQObject);
      R__insp.InspectMember(fQObject, "fQObject.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_prod", &m_prod);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_SCTProducer(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::SCTProducer : new ::SCTProducer;
   }
   static void *newArray_SCTProducer(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::SCTProducer[nElements] : new ::SCTProducer[nElements];
   }
   // Wrapper around operator delete
   static void delete_SCTProducer(void *p) {
      delete ((::SCTProducer*)p);
   }
   static void deleteArray_SCTProducer(void *p) {
      delete [] ((::SCTProducer*)p);
   }
   static void destruct_SCTProducer(void *p) {
      typedef ::SCTProducer current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_SCTProducer(TBuffer &buf, void *obj) {
      ((::SCTProducer*)obj)->::SCTProducer::Streamer(buf);
   }
} // end of namespace ROOT for class ::SCTProducer

/********************************************************
* SCTDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableSCTDict();

extern "C" void G__set_cpp_environmentSCTDict() {
  G__add_ipath("../../include");
  G__cpp_reset_tagtableSCTDict();
}
#include <new>
extern "C" int G__cpp_dllrevSCTDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SCTProducer */
static int G__SCTDict_269_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const SCTProducer*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((SCTProducer*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((SCTProducer*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((SCTProducer*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((SCTProducer*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G__va_arg_buf G__va_arg_bufobj;
   G__va_arg_put(&G__va_arg_bufobj, libp, 2);
      ((SCTProducer*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), G__va_arg_bufobj);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Destroyed();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->ChangedBy((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Message((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SCTProducer* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new SCTProducer((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
   } else {
     p = new((void*) gvp) SCTProducer((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SCTDictLN_SCTProducer));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SCTProducer* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SCTProducer[n];
     } else {
       p = new((void*) gvp) SCTProducer[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SCTProducer;
     } else {
       p = new((void*) gvp) SCTProducer;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SCTDictLN_SCTProducer));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Connect2RunControl((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->getConnectionStatus());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->ConfigurationSatus());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((SCTProducer*) G__getstructoffset())->getConfiguration((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((SCTProducer*) G__getstructoffset())->getConfiguration((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (char*) G__int(libp->para[2]), (Int_t) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->createNewEvent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->setTimeStamp((unsigned long long) G__ULonglong(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->setTimeStamp2Now();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->setTag((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->AddPlane2Event((unsigned int) G__int(libp->para[0]), *(vector<unsigned char>*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->AddPlane2Event((unsigned int) G__int(libp->para[0]), (const bool*) G__int(libp->para[1])
, (size_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->sendEvent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->send_start_run();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->send_onStart();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->send_onConfigure();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->send_onStop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->send_OnTerminate();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->checkStatus();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->getOnStart());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->setOnStart((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->getOnConfigure());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->setOnconfigure((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->getOnStop());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->setOnStop((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SCTProducer*) G__getstructoffset())->getOnTerminate());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->setOnTerminate((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SCTProducer::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SCTProducer::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SCTProducer::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SCTProducer::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const SCTProducer*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SCTProducer*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SCTProducer::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SCTProducer::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SCTProducer::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SCTDict_269_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SCTProducer::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SCTProducer G__TSCTProducer;
static int G__SCTDict_269_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SCTProducer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SCTProducer*) (soff+(sizeof(SCTProducer)*i)))->~G__TSCTProducer();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SCTProducer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SCTProducer*) (soff))->~G__TSCTProducer();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SCTProducer */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSCTDict {
 public:
  G__Sizep2memfuncSCTDict(): p(&G__Sizep2memfuncSCTDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSCTDict::*p)();
};

size_t G__get_sizep2memfuncSCTDict()
{
  G__Sizep2memfuncSCTDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSCTDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSCTDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("iterator<iterator_traits<string::iterator>::iterator_category,iterator_traits<string::iterator>::value_type,iterator_traits<string::iterator>::difference_type,iterator_traits<string::iterator>::pointer,iterator_traits<string::iterator>::reference>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,char,long,char*>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<string::const_iterator>::iterator_category,iterator_traits<string::const_iterator>::value_type,iterator_traits<string::const_iterator>::difference_type,iterator_traits<string::const_iterator>::pointer,iterator_traits<string::const_iterator>::reference>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SCTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SCTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SCTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__SCTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SCTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SCTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SCTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__SCTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SCTProducer */
static void G__setup_memvarSCTProducer(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SCTDictLN_SCTProducer));
   { SCTProducer *p; p=(SCTProducer*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SCTDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SCTDictLN_SCTProducercLcLProducer_PImpl),-1,-1,4,"m_prod=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SCTDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSCTDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSCTProducer(void) {
   /* SCTProducer */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SCTDictLN_SCTProducer));
   G__memfunc_setup("GetListOfSignals",1602,G__SCTDict_269_0_1, 85, G__get_linked_tagnum(&G__SCTDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__SCTDict_269_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__SCTDict_269_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,G__SCTDict_269_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LowPriority",1172,G__SCTDict_269_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EmitVA",550,G__SCTDict_269_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__SCTDict_269_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,G__SCTDict_269_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangedBy",869,G__SCTDict_269_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Message",709,G__SCTDict_269_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SCTProducer",1070,G__SCTDict_269_0_26, 105, G__get_linked_tagnum(&G__SCTDictLN_SCTProducer), -1, 0, 2, 1, 1, 0, 
"C - - 10 - name C - - 10 - runcontrol", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SCTProducer",1070,G__SCTDict_269_0_27, 105, G__get_linked_tagnum(&G__SCTDictLN_SCTProducer), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect2RunControl",1810,G__SCTDict_269_0_28, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - name C - - 10 - runcontrol", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getConnectionStatus",2004,G__SCTDict_269_0_29, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ConfigurationSatus",1896,G__SCTDict_269_0_30, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getConfiguration",1688,G__SCTDict_269_0_31, 105, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - tag i - - 0 - DefaultValue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getConfiguration",1688,G__SCTDict_269_0_32, 105, -1, -1, 0, 4, 1, 1, 0, 
"C - - 10 - tag C - - 10 - defaultValue "
"C - - 0 - returnBuffer i - 'Int_t' 0 - sizeOfReturnBuffer", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("createNewEvent",1440,G__SCTDict_269_0_33, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTimeStamp",1248,G__SCTDict_269_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "m - - 0 - TimeStamp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTimeStamp2Now",1606,G__SCTDict_269_0_35, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setTag",616,G__SCTDict_269_0_36, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - tag C - - 10 - Value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddPlane2Event",1325,G__SCTDict_269_0_37, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - - 0 - - u 'vector<unsigned char,allocator<unsigned char> >' 'vector<unsigned char>' 11 - inputVector", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddPlane2Event",1325,G__SCTDict_269_0_38, 121, -1, -1, 0, 3, 1, 1, 0, 
"h - - 0 - - G - - 10 - inputVector "
"h - 'size_t' 0 - Elements", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("sendEvent",940,G__SCTDict_269_0_39, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("send_start_run",1515,G__SCTDict_269_0_40, 121, -1, -1, 0, 0, 1, 1, 0, "", "async", (void*) NULL, 0);
   G__memfunc_setup("send_onStart",1268,G__SCTDict_269_0_41, 121, -1, -1, 0, 0, 1, 1, 0, "", "sync ", (void*) NULL, 0);
   G__memfunc_setup("send_onConfigure",1672,G__SCTDict_269_0_42, 121, -1, -1, 0, 0, 1, 1, 0, "", "sync", (void*) NULL, 0);
   G__memfunc_setup("send_onStop",1164,G__SCTDict_269_0_43, 121, -1, -1, 0, 0, 1, 1, 0, "", "sync", (void*) NULL, 0);
   G__memfunc_setup("send_OnTerminate",1647,G__SCTDict_269_0_44, 121, -1, -1, 0, 0, 1, 1, 0, "", "sync ", (void*) NULL, 0);
   G__memfunc_setup("checkStatus",1154,G__SCTDict_269_0_45, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getOnStart",1035,G__SCTDict_269_0_46, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setOnStart",1047,G__SCTDict_269_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - newStat", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getOnConfigure",1439,G__SCTDict_269_0_48, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setOnconfigure",1483,G__SCTDict_269_0_49, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - newStat", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getOnStop",931,G__SCTDict_269_0_50, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setOnStop",943,G__SCTDict_269_0_51, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - newStat", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getOnTerminate",1446,G__SCTDict_269_0_52, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setOnTerminate",1458,G__SCTDict_269_0_53, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - newStat", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__SCTDict_269_0_54, 85, G__get_linked_tagnum(&G__SCTDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SCTProducer::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__SCTDict_269_0_55, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SCTProducer::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__SCTDict_269_0_56, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SCTProducer::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__SCTDict_269_0_57, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SCTProducer::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__SCTDict_269_0_58, 85, G__get_linked_tagnum(&G__SCTDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__SCTDict_269_0_59, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__SCTDict_269_0_60, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__SCTDict_269_0_61, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__SCTDict_269_0_62, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SCTProducer::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__SCTDict_269_0_63, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SCTProducer::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__SCTDict_269_0_64, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SCTProducer::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__SCTDict_269_0_65, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SCTProducer::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~SCTProducer", 1196, G__SCTDict_269_0_66, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSCTDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSCTDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSCTDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SCTDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR = { "iterator<random_access_iterator_tag,char,long,char*,char&>" , 115 , -1 };
G__linked_taginfo G__SCTDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR = { "vector<unsigned char,allocator<unsigned char> >" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_SCTProducer = { "SCTProducer" , 99 , -1 };
G__linked_taginfo G__SCTDictLN_SCTProducercLcLProducer_PImpl = { "SCTProducer::Producer_PImpl" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSCTDict() {
  G__SCTDictLN_TClass.tagnum = -1 ;
  G__SCTDictLN_TBuffer.tagnum = -1 ;
  G__SCTDictLN_TMemberInspector.tagnum = -1 ;
  G__SCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR.tagnum = -1 ;
  G__SCTDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR.tagnum = -1 ;
  G__SCTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__SCTDictLN_TList.tagnum = -1 ;
  G__SCTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__SCTDictLN_TQObjSender.tagnum = -1 ;
  G__SCTDictLN_SCTProducer.tagnum = -1 ;
  G__SCTDictLN_SCTProducercLcLProducer_PImpl.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSCTDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SCTDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_vectorlEunsignedsPcharcOallocatorlEunsignedsPchargRsPgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_TList);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_TQObjSender);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SCTDictLN_SCTProducer),sizeof(SCTProducer),-1,34048,(char*)NULL,G__setup_memvarSCTProducer,G__setup_memfuncSCTProducer);
   G__get_linked_tagnum_fwd(&G__SCTDictLN_SCTProducercLcLProducer_PImpl);
}
extern "C" void G__cpp_setupSCTDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSCTDict()");
  G__set_cpp_environmentSCTDict();
  G__cpp_setup_tagtableSCTDict();

  G__cpp_setup_inheritanceSCTDict();

  G__cpp_setup_typetableSCTDict();

  G__cpp_setup_memvarSCTDict();

  G__cpp_setup_memfuncSCTDict();
  G__cpp_setup_globalSCTDict();
  G__cpp_setup_funcSCTDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSCTDict();
  return;
}
class G__cpp_setup_initSCTDict {
  public:
    G__cpp_setup_initSCTDict() { G__add_setup_func("SCTDict",(G__incsetup)(&G__cpp_setupSCTDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSCTDict() { G__remove_setup_func("SCTDict"); }
};
G__cpp_setup_initSCTDict G__cpp_setup_initializerSCTDict;

