#!/bin/bash
#CACTUS
export CACTUS_ROOT=extern/cactus
export CACTUS_BUILD_ROOT=${CACTUS_ROOT}

#extern/erlang
export EXTERN_ERLANG_PREFIX=${CACTUS_BUILD_ROOT}/cactuscore/extern/erlang/RPMBUILD/SOURCES
export EXTERN_ERLANG_BIN_PREFIX=${EXTERN_ERLANG_PREFIX}/bin

#extern/boost
export EXTERN_BOOST_PREFIX=${CACTUS_BUILD_ROOT}/cactuscore/extern/boost/RPMBUILD/SOURCES
export EXTERN_BOOST_INCLUDE_PREFIX=${EXTERN_BOOST_PREFIX}/include
export EXTERN_BOOST_LIB_PREFIX=${EXTERN_BOOST_PREFIX}/lib

#extern/pugixml
export EXTERN_PUGIXML_PREFIX=${CACTUS_BUILD_ROOT}/cactuscore/extern/pugixml/RPMBUILD/SOURCES
export EXTERN_PUGIXML_INCLUDE_PREFIX=${EXTERN_PUGIXML_PREFIX}/include
export EXTERN_PUGIXML_LIB_PREFIX=${EXTERN_PUGIXML_PREFIX}/lib

#uhal/grammars
export UHAL_GRAMMARS_PREFIX=${CACTUS_BUILD_ROOT}/cactuscore/uhal/grammars/
export UHAL_GRAMMARS_INCLUDE_PREFIX=${UHAL_GRAMMARS_PREFIX}/include
export UHAL_GRAMMARS_LIB_PREFIX=${UHAL_GRAMMARS_PREFIX}/lib
#uhal/log
export UHAL_LOG_PREFIX=${CACTUS_BUILD_ROOT}/cactuscore/uhal/log/
export UHAL_LOG_INCLUDE_PREFIX=${UHAL_LOG_PREFIX}/include
export UHAL_LOG_LIB_PREFIX=${UHAL_LOG_PREFIX}/lib

#uhal/uhal
export UHAL_UHAL_PREFIX=${CACTUS_BUILD_ROOT}/cactuscore/uhal/uhal/
export UHAL_UHAL_INCLUDE_PREFIX=${UHAL_UHAL_PREFIX}/include
export UHAL_UHAL_LIB_PREFIX=${UHAL_UHAL_PREFIX}/lib
export LD_LIBRARY_PATH=${EXTERN_BOOST_LIB_PREFIX}:${EXTERN_PUGIXML_LIB_PREFIX}:${UHAL_LOG_LIB_PREFIX}:${UHAL_GRAMMARS_LIB_PREFIX}:${UHAL_UHAL_LIB_PREFIX} 

./bin/miniTLU_Producer.exe

