# example init file: Ex0.ini
[LogCollector.log]
EULOG_GUI_LOG_FILE_PATTERN = myexample_$12D.log

[Producer.my_pd0]
EX0_DEV_LOCK_PATH = /tmp/mydev0.lock
ControllerType = V2718
#LinkOrPid = 49086
LinkOrPid = 0

[DataCollector.my_dc]
Class = HidraDataCollector
FilePattern = /home/eudaq/eudaq_hidra_STV/eudaq_hidra/user/example/pavia/data/run$6R.raw

#[Producer.my_pd1]
#EX0_DEV_LOCK_PATH = /tmp/mydev1.lock
