#!/bin/bash

source build_env.sh

printf '\033[1;32;48m \t STARTING DAQ LOCALLY\033[0m \n'
echo $(date)
printf '\033[22;33m\t Cleaning up first...  \033[0m \n'

if [ -f KILLRUN.local ]
then
    sh KILLRUN.local
else
    sh KILLRUN
fi

printf '\033[22;31m\t End of killall \033[0m \n'

sleep 1

ls

######################################################################
#if [ -n "`ls data/run*.raw`" ]
#then
#    printf '\033[22;33m\t Making sure all data files are properly writeprotected \033[0m \n'
#    chmod a=rw data/run*.raw
#    printf '\033[22;32m\t ...Done!\033[0m \n'
#fi

cd $DATADIR

#=====================================================================
printf '\033[22;33m\t Starting Subprocesses \033[0m \n'
#=====================================================================
######################################################################
# euRun
###############
printf '\033[22;33m\t RunControl \033[0m \n'
$EUDAQBIN/euRun -x 0 -y 0 -w 650 -g 550 -a tcp://$RCPORT &
sleep 1
######################################################################
# euLog
###############
printf '\033[22;33m\t Logger  \033[0m \n'
$EUDAQBIN/euLog -x 0 -y 550 -w 1500 -g 450 -r tcp://$HOSTIP:44000 | tee $LOGFILE &
sleep 3

#printf '\033[22;33m\t OnlineMonitor  \033[0m \n'
#$EUDAQBIN/OnlineMon  -r tcp://$HOSTIP:$RCPORT &
#sleep 3

######################################################################
# DataCollector
###############
printf '\033[22;33m\t TestDataCollector \033[0m \n'
#xterm -sb -sl 1000 -geom 80x10-480-900 -fn fixed -T "Data Collector" -e "./caliceDataCollector -r tcp://$HOSTIP:$RCPORT" &
$EUDAQBIN/TestDataCollector -n CaliceDataCollector -r tcp://$HOSTIP:$RCPORT &
sleep 3

printf '\033[22;33m\t  caliceProducer-scintillator  \033[0m \n'
$EUDAQBIN/caliceProducer -n CaliceSc -r tcp://$TLUIP:$RCPORT &
#-r tcp://$HOSTIP:$RCPORT &
sleep 3


#printf '\033[22;33m\t  caliceProducer-scintillator  \033[0m \n'
#$CALEUDAQ/caliceProducer -n CaliceSc -r tcp://$TLUIP:$RCPORT &

#$EUDAQBIN/Converter -t calice -a -r tcp://$TLUIP:$RCPORT &
#sleep 3


printf ' \n'
printf ' \n'
printf ' \n'
printf '\033[1;32;48m\t ...Done!\033[0m \n'
printf '\033[1;32;48mSTART OF DAQ COMPLETE\033[0m \n'
