#include "tlu/TLUAddresses.hh"
#include "tlu/TLU_address_map.h"

#define REGISTERED_BUFFER_POINTER_ADDRESS_BASE REGISTERED_BUFFER_POINTER_ADDRESS_0
#define REGISTERED_BUFFER_POINTER_ADDRESS_BYTES 2
#define REGISTERED_TIMESTAMP_ADDRESS_BASE REGISTERED_TIMESTAMP_ADDRESS_0
#define REGISTERED_TIMESTAMP_ADDRESS_BYTES 8
#define REGISTERED_TRIGGER_COUNTER_ADDRESS_BASE REGISTERED_TRIGGER_COUNTER_ADDRESS_0
#define REGISTERED_TRIGGER_COUNTER_ADDRESS_BYTES 4
#define BUFFER_POINTER_ADDRESS_BASE BUFFER_POINTER_ADDRESS_0
#define BUFFER_POINTER_ADDRESS_BYTES 2
#define TIMESTAMP_ADDRESS_BASE TIMESTAMP_ADDRESS_0
#define TIMESTAMP_ADDRESS_BYTES 8
#define TRIGGER_COUNTER_ADDRESS_BASE TRIGGER_COUNTER_ADDRESS_0
#define TRIGGER_COUNTER_ADDRESS_BYTES 4
#define TRIGGER_IN0_COUNTER_BASE TRIGGER_IN0_COUNTER_0
#define TRIGGER_IN0_COUNTER_BYTES 2
#define TRIGGER_IN1_COUNTER_BASE TRIGGER_IN1_COUNTER_0
#define TRIGGER_IN1_COUNTER_BYTES 2
#define TRIGGER_IN2_COUNTER_BASE TRIGGER_IN2_COUNTER_0
#define TRIGGER_IN2_COUNTER_BYTES 2
#define TRIGGER_IN3_COUNTER_BASE TRIGGER_IN3_COUNTER_0
#define TRIGGER_IN3_COUNTER_BYTES 2
#define REGISTERED_PARTICLE_COUNTER_ADDRESS_BASE REGISTERED_PARTICLE_COUNTER_ADDRESS_0
#define REGISTERED_PARTICLE_COUNTER_ADDRESS_BYTES 4

#define DUT_I2C_BUS_SELECT_ADDRESS EUDAQ_TLU_MISSING
#define DUT_I2C_BUS_DATA_ADDRESS EUDAQ_TLU_MISSING
#define I2C_BUS_MOTHERBOARD EUDAQ_TLU_MISSING
#define I2C_BUS_MOTHERBOARD_LED_IO EUDAQ_TLU_MISSING


namespace tlu {

#define EUDAQ_TLU_REG(r) r,

  TLUAddresses v0_1 = {
    EUDAQ_TLU_REGISTERS
  };

}
