/********************************************************************
* RSCTDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RSCTDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevRSCTDict();
extern G__DLLEXPORT void G__set_cpp_environmentRSCTDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableRSCTDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceRSCTDict();
extern G__DLLEXPORT void G__cpp_setup_typetableRSCTDict();
extern G__DLLEXPORT void G__cpp_setup_memvarRSCTDict();
extern G__DLLEXPORT void G__cpp_setup_globalRSCTDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncRSCTDict();
extern G__DLLEXPORT void G__cpp_setup_funcRSCTDict();
extern G__DLLEXPORT void G__cpp_setupRSCTDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "prod.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RSCTDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__RSCTDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__RSCTDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RSCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RSCTDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__RSCTDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__RSCTDictLN_TList;
extern G__linked_taginfo G__RSCTDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RSCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RSCTDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__RSCTDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__RSCTDictLN_TQObjSender;
extern G__linked_taginfo G__RSCTDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__RSCTDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RSCTDictLN_iteratorlErandom_access_iterator_tagcOTStringcOlongcOTStringmUcOTStringaNgR;
extern G__linked_taginfo G__RSCTDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__RSCTDictLN_prod;

/* STUB derived class for protected member access */
